#' Generates a semantic icon with a specific color and link that opens on a new tab when clicked.
#'
#' @param icon A semantic icon name
#' @param color A valid css color
#' @param link A valid html link
#' @return A UI tag that can be used in [shinyUI] functions.
#'
#' @note See \url{https://fomantic-ui.com/elements/icon.html}
#'   for a full list of available icons
#'
#' @family uifragment functions
#' @seealso [pageBackground(), darkify(), generateSourceImage()]
linkIcon <- function(icon, color, link) {
  tags$a(icon(class = glue::glue("large {icon}"), style = glue::glue("color: {color}")), target = "_blank", href = link)
}

#' Creates a image output that can be used as a support element for html background elements.
#'
#' @return A UI tag that can be used in [shinyUI] functions.
#'
#' @family uifragment functions
#' @seealso [linkIcon(), darkify(), generateSourceImage()]
pageBackground <- function() {
  imageOutput("bodyBackground") %>% tagAppendAttributes(class = "body-background")
}

#' Adds semantic darkmode to the eement generated by the callback. Used to
#'   add dark mode to elements that dont have it out of the box.
#'
#' @param callback Any function that returns a UI definition
#' @param type A type to add to the genenrated UI tag. Used by some semantic elements
#'   to idetify darkmode elements
#' @param ... Other arguments that are accepted by the callback function
#' @return A UI tag generated by callback, with the added darkmode attributes.
#'
#' @family uifragment functions
#' @seealso [linkIcon(), pageBackground(), generateSourceImage()]
darkify <- function(callback, ..., type = "inverted") {
  callback(...) %>% tagAppendAttributes(class = "inverted", type = type)
}

#' Processes a url into a temporary file that can be used as the result of an image output.
#'
#' @param src Image URL
#' @param name The name used by the image for the alt text attribute
#' @return A UI tag generated by callback, with the added darkmode attributes.
#'
#' @family uifragment functions
#' @seealso [linkIcon(), pageBackground(), darkify()]
generateSourceImage <- function(src, name) {
  outfile <- tempfile(fileext='.png')
  jpeg(outfile, width = baseSize, height = baseSize)
  save.image(src, outfile)
  dev.off()

  list(src = outfile, alt = name)
}
